import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { Background } from "@/components/Background";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/cloud.png" />
      </head>
      <body className={montserrat.className}>
        <Header />
        <div className="container mx-auto h-[calc(100vh-64px)]">{children}</div>
        <Background />
      </body>
    </html>
  );
}
